### ISSUE TITLE
Where to properly add a custom.css file to Mercado Pago?

### ISSUE THREAD

**Issue by danielsami** [mercadopago/cart-magento#177]
Hello, 

where to properly add a custom.css file to Mercado Pago? 

The checkout page https://domain.com/mercadopago/pay/ comes aligned left, way left, being blocked in part by the "share this" banner.  I want to text-align:center

I added the following to: /home/domain/public_html/skin/frontend/base/default/mercadopago/css/custom.css:

```
    /* CUSTOMIZATION 11-9-2016: ON PAGE https://domain.com/mercadopago/pay/ CONTENT HAS BEEN
    CENTERED */

     .main {
          text-align:center;
     }

```
This works, but I want it added to a custom.css file to avoid being overwritten by future extension updates.

Thank you!

**Comment by imasson** [comment]
Hi @danielsami !
In order to add custom css to a page, you can use a custom layout.
As you can see in this file 
[https://github.com/mercadopago/cart-magento/blob/master/1.6.x-1.9.x/app/design/frontend/base/default/layout/mercadopago.xml
]()
You could do something similar but using mercadopago_pay_index
`
<mercadopago_pay_index>`
 `       <reference name="head">`
`            <action method="addCss">`
`                <stylesheet>yourcustomfolder/css/custom.css</stylesheet>`
`            </action>`
`        </reference>`
`</mercadopago_pay_index>`

I hope it helps!
