### ISSUE TITLE
Confirmation e-mail isn't being sent

### ISSUE THREAD

**Issue by SoulSin** [mercadopago/cart-magento#48]
Hello.

For some reason, every time someone purchases something from my shop using this MercadoPago Express module, both client and me aren't receiving the Purchase Confirmation E-mail.

I'ts worth mentioning that I can't detect any bug in the process itself (it works normally, the client is redirected to the right page and MP successfully confirms the payment on mercadopago.com).
Its just that, for some reason, no one receives the confirmation e-mail after the checkout.

Any Ideas on how to solve this issue?

Note: Only happens with MP Module, other payment methods like Bank Deposit and PagSeguro it works fine. (we never tested Paypal)

**Comment by SoulSin** [comment]
Seens that there is a misspell on app/code/community/Mpexpress/controllers/IpnController.php

On line 66
```case 'approved':
	    $createinvoice = Mage::getModel('mpexpress/Express')->getConfigData('auto_create_inovice');```

Shouldn't be "auto_create_invoice" ?

Then again, that alone doesn't solve the problem at hand.

**Comment by tiosolid** [comment]
This is by design (not sure exactly why). Every payment module that redirects to another page after the checkout (like paypal and MercadoPago) does not trigger the "order confirmation email".

if you check line 811 in the following magento core file:
app/code/core/Mage/Checkout/Model/Type/Onepage.php 

you will see:
```PHP
            /**
             * we only want to send to customer about new order when there is no redirect to third party
             */
            if (!$redirectUrl && $order->getCanSendNewEmailFlag()) {
                try {
                    $order->queueNewOrderEmail();
                } catch (Exception $e) {
                    Mage::logException($e);
                }
            }
```

I fixed this "bug" adding the line:
```PHP
$order->sendNewOrderEmail();
```

To the app/code/community/Mpexpress/Model/Express.php file. This will trigger the new order email code and update all the required fields in the order itself.

See the following commit for more information:
https://github.com/tiosolid/cart-magento/commit/ef47506ad2659281cf5eb8c467854cb9847bef24

**Comment by SoulSin** [comment]
Hello tiosolid.

Your change worked like a charm.

Thanks for the attention.
