### ISSUE TITLE
SSL3 API Updates

### ISSUE THREAD

**Issue by barbazul** [mercadopago/cart-magento#58]
Hi, 

How is this module affected by March 24th API changes regarding SSL3 usage.

Is SSL3 forced in any (current or older) version of it?

**Comment by ekupelian** [comment]
If I understood correctly, maybe a member of MeLi can correct or confirm this, the pull request #57 updated the CURL options to remove the hardcoded option to use SSLv3.

So my understanding is that once SSL3 is disabled, previous versions of this module won't work. If so, this should get a lot more attention and **should be notified** on the *Readme.md* in a very noticeable manner, along with a patch or a how-to explaining the change that should be applied.

I'd really like an official explanation on this matter, and what actions should be taken, from the team.

**Comment by barbazul** [comment]
That PR is 1 day old. So ALL modules out in the wild should be updated then.

LCDTMAB

**Comment by ekupelian** [comment]
If my understanding of the problem is correct, so are you ;)
Some one from MercadoLibre cares to comment please ?

HDMPsAA

**Comment by sebagun** [comment]
@ekupelian you are totally right. As we've explained in our developers forum (http://developers.mercadopago.com/developers-forum?place=topic%2Fmercadopago-developers%2FQjcKZ0LBpn8%2Fdiscussion), the support for SSL3 protocol will be shut down on March 24th, this is because recent investigations that have discovered that the protocol is insecure.
All SDKs have been rewritten to ensure proper comunication, right now and when the support for SSL3 ends.

So please, if you are using any older version of the SDK, update it to ensure that you'll still receiving payments without problems.

Best regards

**Comment by ekupelian** [comment]
Thank you for confirming @sebagun !
